### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by tgeene** [lukejagodzinski/heroku-buildpack-meteor#1]
So I followed the instructions and all I get is this error.

```
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.
```

**Comment by lukejagodzinski** [comment]
So probably the problem lies somewhere else. I will help you if you post here some logs from `heroku logs` command. One more thing you have to do, that I didn't describe in README, is adding MongoHQ package and setting `MONGO_URL` to the same as `MONGOHQ_URL`. Maybe doing that will solve your problem. However I'm gonna create video tutorial soon on how to deploy Meteor application to Heroku server. 

I've added few lines to README about MongoHQ: https://github.com/jagi/heroku-buildpack-meteor/blob/master/README.md

**Comment by tgeene** [comment]
So I did everything you said in the new steps and here is the logs.

```
Jul 31 11:32:35 infoodsys heroku/web.1:  State changed from down to starting 
Jul 31 11:32:47 infoodsys app/web.1:      at null.<anonymous> (/app/.meteor/local/build/programs/server/npm/mongo-livedata/main/node_modules/mongodb/lib/mongodb/connection/server.js:536:74) 
Jul 31 11:32:47 infoodsys app/web.1:      at emit (events.js:106:17) 
Jul 31 11:32:47 infoodsys app/web.1:      at null.<anonymous> (/app/.meteor/local/build/programs/server/npm/mongo-livedata/main/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15) 
Jul 31 11:32:47 infoodsys app/web.1:      at emit (events.js:98:17) 
Jul 31 11:32:47 infoodsys app/web.1:      at Socket.<anonymous> (/app/.meteor/local/build/programs/server/npm/mongo-livedata/main/node_modules/mongodb/lib/mongodb/connection/connection.js:516:10) 
Jul 31 11:32:47 infoodsys app/web.1:      at Socket.emit (events.js:95:17) 
Jul 31 11:32:47 infoodsys app/web.1:      at net.js:833:16 
Jul 31 11:32:47 infoodsys app/web.1:      at process._tickCallback (node.js:419:13) 
Jul 31 11:32:47 infoodsys app/web.1:  Exception in callback of async function: Error: failed to connect to [heroku:NaN] 
Jul 31 11:32:49 infoodsys heroku/web.1:  Starting process with command `node .meteor/local/build/main.js` 
Jul 31 11:33:44 infoodsys heroku/web.1:  Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch 
Jul 31 11:33:44 infoodsys heroku/web.1:  Stopping process with SIGKILL 
Jul 31 11:33:47 infoodsys heroku/web.1:  State changed from starting to crashed 
Jul 31 11:33:47 infoodsys heroku/web.1:  State changed from crashed to starting 
Jul 31 11:33:49 infoodsys heroku/router:  at=error code=H20 desc="App boot timeout" method=GET path="/" host=infoodsys.herokuapp.com request_id=8513d358-f482-4727-b199-f35b64761578 fwd="24.234.234.93" dyno= connect= service= status=503 bytes= 
Jul 31 11:33:51 infoodsys heroku/web.1:  Process exited with status 137 
Jul 31 11:33:56 infoodsys app/web.1:  Exception in callback of async function: Error: failed to connect to [heroku:NaN] 
Jul 31 11:33:56 infoodsys app/web.1:      at null.<anonymous> (/app/.meteor/local/build/programs/server/npm/mongo-livedata/main/node_modules/mongodb/lib/mongodb/connection/server.js:536:74) 
Jul 31 11:33:56 infoodsys app/web.1:      at emit (events.js:106:17) 
Jul 31 11:33:56 infoodsys app/web.1:      at null.<anonymous> (/app/.meteor/local/build/programs/server/npm/mongo-livedata/main/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15) 
Jul 31 11:33:56 infoodsys app/web.1:      at emit (events.js:98:17) 
Jul 31 11:33:56 infoodsys app/web.1:      at Socket.<anonymous> (/app/.meteor/local/build/programs/server/npm/mongo-livedata/main/node_modules/mongodb/lib/mongodb/connection/connection.js:516:10) 
Jul 31 11:33:56 infoodsys app/web.1:      at Socket.emit (events.js:95:17) 
Jul 31 11:33:56 infoodsys app/web.1:      at net.js:833:16 
Jul 31 11:33:56 infoodsys app/web.1:      at process._tickCallback (node.js:419:13) 
Jul 31 11:33:59 infoodsys heroku/web.1:  Starting process with command `node .meteor/local/build/main.js` 
Jul 31 11:34:49 infoodsys heroku/router:  at=error code=H20 desc="App boot timeout" method=GET path="/" host=infoodsys.herokuapp.com request_id=adba1272-3793-4f01-8283-8e3ad7d7841a fwd="24.234.234.93" dyno= connect= service= status=503 bytes= 
Jul 31 11:34:58 infoodsys heroku/router:  at=error code=H10 desc="App crashed" method=GET path="/" host=infoodsys.herokuapp.com request_id=a1bad0dd-c57a-4589-a097-49782ed57943 fwd="24.234.234.93" dyno= connect= service= status=503 bytes= 
Jul 31 11:34:59 infoodsys heroku/router:  at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=infoodsys.herokuapp.com request_id=69dd6c47-dad8-4bfb-a354-07f90c07b4f5 fwd="24.234.234.93" dyno= connect= service= status=503 bytes= 
Jul 31 11:34:59 infoodsys heroku/web.1:  Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch 
Jul 31 11:34:59 infoodsys heroku/web.1:  Stopping process with SIGKILL 
Jul 31 11:34:59 infoodsys heroku/web.1:  Process exited with status 137 
```

I am not much of a server person, so most of this looks like gibberish to me.

Any help is greatly appreciated.

**Comment by lukejagodzinski** [comment]
Ok so the problem was probably with the ROOT_URL. I forgot to write that URL has to start from http://. However I've made short movie showing how I'm creating default Meteor app and uploading it to Heroku server http://youtu.be/perOYgDvgCw
Hope that now it's gonna work :)

**Comment by tgeene** [comment]
OMG, I love you! Thank you so much for the help, you are amazing!

**Comment by lukejagodzinski** [comment]
Hehe no problem :) I know how hard it is to configure it. I've spend 2 days doing it but it's good to share this knowledge with others :)

**Comment by praneybehl** [comment]
Great video @jagi nice work. Wondering if this works with Meteor V0.9.x as well?

**Comment by lukejagodzinski** [comment]
Thanks. Unfortunately it doesn't work with Meteor 0.9.x. I have to fix it. Probably there is problem with downloading Meteor, not with configuration of Heroku. I will let you know here. I'm a little bit busy right now so you have to wait.

**Comment by praneybehl** [comment]
No worries mate, thanks for your reply. :)

**Comment by tdameh** [comment]
Thanks for sharing, the only problem that it works using Meteor 0.8.3 not 0.9.*

**Comment by lukejagodzinski** [comment]
Yes indeed I haven't made it work with newest version yet. I'm going to do it soon. I have a lot of work right now.

**Comment by colllin** [comment]
```
WARNING: 'bundle' has been deprecated. Use 'build' instead.
```

during build and then stops without returning...

**Comment by lukejagodzinski** [comment]
I know this. I've tried quickly fix this buildpack but without success. It requires more time to accomplish. I will soon do it because I will need to build my own app. I will post comment here when I'm done.

**Comment by colllin** [comment]
@jagi I saw your `develop` branch.  Thanks for trying.

Actually I browsed most every buildpack available and found one that is up-to-date for Meteor 0.9.3.  Check out the horse one.
https://github.com/AdmitHub/meteor-buildpack-horse

You might need to back out some changes you made for your buildpack, for example I needed to remove the Procfile.

**Comment by lukejagodzinski** [comment]
If it works then there's no point of upgrading my build pack :-). Thanks for sharing.

**Comment by lukejagodzinski** [comment]
I've made my own version of buildpack, following some rules from https://github.com/AdmitHub/meteor-buildpack-horse. Checkout README for more information on how to use it. If you have any suggestions, feel free to post issue.

**Comment by tgeene** [comment]
This is probably not related, but I pushed and update to my site the other day and it crashed. I have spent 2 days looking for a solution with no avail. Could you possibly help me with this?

Error Logs:

```
Nov 20 16:00:59 infoodsys heroku/web.1:  State changed from crashed to starting 
Nov 20 16:01:03 infoodsys heroku/web.1:  Starting process with command `.heroku/bin/node /app/.meteor/heroku_build/app/main.js` 
Nov 20 16:01:04 infoodsys app/web.1:  module.js:340 
Nov 20 16:01:04 infoodsys app/web.1:      throw err; 
Nov 20 16:01:04 infoodsys app/web.1:            ^ 
Nov 20 16:01:04 infoodsys app/web.1:  Error: Cannot find module '/app/.meteor/heroku_build/app/main.js' 
Nov 20 16:01:04 infoodsys app/web.1:      at Function.Module._resolveFilename (module.js:338:15) 
Nov 20 16:01:04 infoodsys app/web.1:      at Function.Module._load (module.js:280:25) 
Nov 20 16:01:04 infoodsys app/web.1:      at Function.Module.runMain (module.js:497:10) 
Nov 20 16:01:04 infoodsys app/web.1:      at startup (node.js:119:16) 
Nov 20 16:01:04 infoodsys app/web.1:      at node.js:906:3 
Nov 20 16:01:05 infoodsys heroku/web.1:  State changed from crashed to starting 
Nov 20 16:01:09 infoodsys heroku/web.1:  Starting process with command `.heroku/bin/node /app/.meteor/heroku_build/app/main.js` 
Nov 20 16:01:10 infoodsys app/web.1:  module.js:340 
Nov 20 16:01:10 infoodsys app/web.1:      throw err; 
Nov 20 16:01:10 infoodsys app/web.1:            ^ 
Nov 20 16:01:10 infoodsys app/web.1:  Error: Cannot find module '/app/.meteor/heroku_build/app/main.js' 
Nov 20 16:01:10 infoodsys app/web.1:      at Function.Module._resolveFilename (module.js:338:15) 
Nov 20 16:01:10 infoodsys app/web.1:      at Function.Module._load (module.js:280:25) 
Nov 20 16:01:10 infoodsys app/web.1:      at Function.Module.runMain (module.js:497:10) 
Nov 20 16:01:10 infoodsys app/web.1:      at startup (node.js:119:16) 
Nov 20 16:01:10 infoodsys app/web.1:      at node.js:906:3 
Nov 20 16:01:11 infoodsys heroku/web.1:  Process exited with status 8 
Nov 20 16:01:11 infoodsys heroku/web.1:  State changed from starting to crashed 
```

It has something to do with the Procfile, but I have no idea how to find the main.js file path.

**Comment by lukejagodzinski** [comment]
Are you sure that you are using my buildpack? I see in logs that you have directory `.meteor/heroku_buildpack` which is not used in this one. It looks like you are using horse buildpack. Try setting buildpack url one more time. You can do it from heroku website.

**Comment by tgeene** [comment]
Yes, I am using your buildpack. I realized that there was an error with the Procfile and kept changing it. And now I don't have the original code that was in it with the path to the main.js file.

**Comment by lukejagodzinski** [comment]
You don't need Procfile any more it's generated automatically so just delete it.

**Comment by tgeene** [comment]
I deleted the Procfile and this is the error I got:

```
Nov 21 09:12:17 infoodsys heroku/slug-compiler:  Slug compilation started 
Nov 21 09:13:24 infoodsys heroku/slug-compiler:  Slug compilation finished 
Nov 21 09:13:24 infoodsys heroku/web.1:  State changed from crashed to starting 
Nov 21 09:13:24 infoodsys heroku/api:  Deploy 8464e42 by xxx@infoodsys.net 
Nov 21 09:13:24 infoodsys heroku/api:  Release v95 created by xxx@infoodsys.net 
Nov 21 09:13:28 infoodsys heroku/web.1:  Starting process with command `.heroku/bin/node .heroku/app/main.js` 
Nov 21 09:13:29 infoodsys app/web.1:  module.js:340 
Nov 21 09:13:29 infoodsys app/web.1:      throw err; 
Nov 21 09:13:29 infoodsys app/web.1:            ^ 
Nov 21 09:13:29 infoodsys app/web.1:  Error: Cannot find module '/app/.heroku/app/main.js' 
Nov 21 09:13:29 infoodsys app/web.1:      at Function.Module._resolveFilename (module.js:338:15) 
Nov 21 09:13:29 infoodsys app/web.1:      at Function.Module._load (module.js:280:25) 
Nov 21 09:13:29 infoodsys app/web.1:      at Function.Module.runMain (module.js:497:10) 
Nov 21 09:13:29 infoodsys app/web.1:      at startup (node.js:119:16) 
Nov 21 09:13:29 infoodsys app/web.1:      at node.js:906:3 
Nov 21 09:13:30 infoodsys heroku/web.1:  State changed from starting to crashed 
Nov 21 09:13:30 infoodsys heroku/web.1:  Process exited with status 8 
Nov 21 09:13:30 infoodsys heroku/web.1:  State changed from crashed to starting 
Nov 21 09:13:34 infoodsys heroku/web.1:  Starting process with command `.heroku/bin/node .heroku/app/main.js` 
Nov 21 09:13:35 infoodsys app/web.1:  module.js:340 
Nov 21 09:13:35 infoodsys app/web.1:      throw err; 
Nov 21 09:13:35 infoodsys app/web.1:            ^ 
Nov 21 09:13:35 infoodsys app/web.1:  Error: Cannot find module '/app/.heroku/app/main.js' 
Nov 21 09:13:35 infoodsys app/web.1:      at Function.Module._resolveFilename (module.js:338:15) 
Nov 21 09:13:35 infoodsys app/web.1:      at Function.Module._load (module.js:280:25) 
Nov 21 09:13:35 infoodsys app/web.1:      at Function.Module.runMain (module.js:497:10) 
Nov 21 09:13:35 infoodsys app/web.1:      at startup (node.js:119:16) 
Nov 21 09:13:35 infoodsys app/web.1:      at node.js:906:3 
Nov 21 09:13:35 infoodsys heroku/web.1:  State changed from starting to crashed 
Nov 21 09:13:36 infoodsys heroku/web.1:  Process exited with status 8 
```

**Comment by tgeene** [comment]
So I was able to change the Procfile to locate the main.js file, but now it can't find the module 'fibers'.

```
Nov 21 13:07:25 infoodsys heroku/slug-compiler:  Slug compilation started 
Nov 21 13:08:45 infoodsys heroku/slug-compiler:  Slug compilation finished 
Nov 21 13:08:45 infoodsys heroku/api:  Deploy c59ef7f by xxx@infoodsys.net 
Nov 21 13:08:45 infoodsys heroku/api:  Release v97 created by xxx@infoodsys.net 
Nov 21 13:08:46 infoodsys heroku/web.1:  State changed from crashed to starting 
Nov 21 13:08:49 infoodsys heroku/web.1:  Starting process with command `.heroku/bin/node .meteor/local/build/main.js` 
Nov 21 13:08:50 infoodsys app/web.1:  module.js:340 
Nov 21 13:08:50 infoodsys app/web.1:      throw err; 
Nov 21 13:08:50 infoodsys app/web.1:            ^ 
Nov 21 13:08:50 infoodsys app/web.1:  Error: Cannot find module 'fibers' 
Nov 21 13:08:50 infoodsys app/web.1:      at Function.Module._resolveFilename (module.js:338:15) 
Nov 21 13:08:50 infoodsys app/web.1:      at Function.Module._load (module.js:280:25) 
Nov 21 13:08:50 infoodsys app/web.1:      at Module.require (module.js:364:17) 
Nov 21 13:08:50 infoodsys app/web.1:      at require (module.js:380:17) 
Nov 21 13:08:50 infoodsys app/web.1:      at Object.<anonymous> (/app/.meteor/local/build/programs/server/boot.js:1:75) 
Nov 21 13:08:50 infoodsys app/web.1:      at Module._compile (module.js:456:26) 
Nov 21 13:08:50 infoodsys app/web.1:      at Object.Module._extensions..js (module.js:474:10) 
Nov 21 13:08:50 infoodsys app/web.1:      at Module.load (module.js:356:32) 
Nov 21 13:08:50 infoodsys app/web.1:      at Function.Module._load (module.js:312:12) 
Nov 21 13:08:50 infoodsys app/web.1:      at Module.require (module.js:364:17) 
Nov 21 13:08:50 infoodsys heroku/web.1:  Process exited with status 8 
Nov 21 13:08:50 infoodsys heroku/web.1:  State changed from starting to crashed 
```

**Comment by lukejagodzinski** [comment]
Do you use any packages that use some NPM dependencies? Could you list here all packages that you added to your Meteor project? I think that the problem is in packages that you use. Have you tried deploying empty Meteor repository?
