### ISSUE TITLE
Application Error : An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

### ISSUE THREAD

**Issue by prachik2** [lukejagodzinski/heroku-buildpack-meteor#3]
2018-07-04T12:11:48.817086+00:00 app[web.1]:     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
2018-07-04T12:11:48.817087+00:00 app[web.1]:     at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
2018-07-04T12:11:48.817089+00:00 app[web.1]:     at new Collection (packages/mongo/collection.js:97:40)
2018-07-04T12:11:48.817091+00:00 app[web.1]:     at new AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
2018-07-04T12:11:48.817082+00:00 app[web.1]:     at new MongoConnection (packages/mongo/mongo_driver.js:169:11)
2018-07-04T12:11:48.817092+00:00 app[web.1]:     at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
2018-07-04T12:11:48.817094+00:00 app[web.1]:     at server_main.js (packages/accounts-base/server_main.js:9:12)
2018-07-04T12:11:48.870548+00:00 heroku[web.1]: Process exited with status 1
2018-07-04T12:21:54.833354+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=chat-fourams.herokuapp.com request_id=ac82f933-e35d-41f9-a7c5-ed4044e2729e fwd="114.143.27.2" dyno= connect= service= status=503 bytes= protocol=https
2018-07-04T12:21:55.169721+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=chat-fourams.herokuapp.com request_id=c9ae5987-e5f9-48cc-8ec4-dcb02c21a998 fwd="114.143.27.2" dyno= connect= service= status=503 bytes= protocol=https

**Comment by prachik2** [comment]
Please Help me out to solve these Application Error

**Comment by lukejagodzinski** [comment]
@prachik2 it's very old repository, for the old Meteor version so it's not gonna work. I'm not using Heroku anymore but I think that you should find some working buildpacks. Maybe they have some official one for Meteor.
